name: Build Documentation and Deploy to GitHub Pages

on:
  push:
    branches:
    - master
    paths:
    - "website/**"
    - "qmapshaper/metadata.txt"

jobs:

  build-deploy:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.6'
        architecture: 'x64'

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install mkdocs
        python3 -m pip install MarkdownHighlight
        python3 -m pip install https://codeload.github.com/mkdocs/mkdocs-bootstrap/zip/master
        python3 -m pip install git+https://github.com/mkdocs/mkdocs-bootswatch
        python3 -m pip install git+https://github.com/it-novum/mkdocs-featherlight.git

    - name: Build
      run: |
        mkdocs build --config-file ./website/mkdocs.yml
        touch website/docs/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GT_TOKEN }}
          publish_dir: ./website/docs
          publish_branch: gh-pages 
