name: Tests for Plugin QMapshaper

on:
  push:
    paths:
    - "qmapshaper/**"
    - ".github/workflows/test_plugin.yaml"
    - "tests/**"

jobs:

  Tests-plugin-QMapshaper:

    runs-on: ubuntu-latest

    container: cahik/vscode-ubuntu-qgis-testing:mapshaper

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Python Path
        run: echo $PYTHONPATH
 
      # - name: Run Tests
      #   run: |
      #     QT_QPA_PLATFORM=offscreen pytest tests --cov=qmapshaper --cov-report=term-missing:skip-covered -rP -vv -s -n1
      
      - name: Run Tests classes
        run: |
          QT_QPA_PLATFORM=offscreen pytest tests/classes --cov=qmapshaper --cov-report=term-missing:skip-covered -rP -vv -s -n1

      - name: Run Tests processing
        run: |
          QT_QPA_PLATFORM=offscreen pytest tests/processing --cov=qmapshaper --cov-report=term-missing:skip-covered -rP -vv -s -n1

      - name: Run Tests gui process
        run: |
          QT_QPA_PLATFORM=offscreen pytest tests/gui/test_interactive_simplifier_process.py --cov=qmapshaper --cov-report=term-missing:skip-covered -rP -vv -s -n1
      
      - name: Run Tests gui tool
        run: |
          QT_QPA_PLATFORM=offscreen pytest tests/gui/test_dialog_tool_interactive_simplifier.py --cov=qmapshaper --cov-report=term-missing:skip-covered -rP -vv -s -n1
      
      